openapi: 3.0.0

info:
  title: Orbit Tracking API
  description: API for managing orbiters in a personal task solar system
  version: 1.0.0

servers:
  - url: https://orbit-api.fly.dev

paths:
  /{user}/api/orbiters:
    post:
      summary: Add a new orbiter to the user's system
      parameters:
        - name: user
          in: path
          required: true
          description: The user’s name or unique identifier
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [orbiter, category, scope, priority]
              properties:
                orbiter:
                  type: string
                  example: "Work Report"
                category:
                  type: string
                  example: "work"
                scope:
                  type: integer
                  example: 10
                priority:
                  type: integer
                  example: 2
      responses:
        "200":
          description: Orbiter added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  starmap:
                    type: string
                    example: "/jamie/api/starmap"
                  orbital_data:
                    type: array
                    items:
                      type: object
                      properties:
                        orbiter:
                          type: string
                        angle:
                          type: integer
                        distance:
                          type: integer
                        size:
                          type: integer
                  log:
                    type: string
                    example: "New celestial object detected in Jamie's system."
    get:
      summary: Retrieve all orbiters for a user
      parameters:
        - name: user
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A list of all orbiters in the user's system
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    orbiter:
                      type: string
                    category:
                      type: string
                    scope:
                      type: integer
                    priority:
                      type: integer
                    angle:
                      type: integer
                    distance:
                      type: integer
                    size:
                      type: integer