name: CI Test Deploy to Fly.io

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH

      - name: Ensure Test App Exists on Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          if ! flyctl apps list | grep -q "orbit-api-pr-${{ github.event.number }}"; then
            echo "Creating test app orbit-api-pr-${{ github.event.number }}..."
            flyctl apps create orbit-api-pr-${{ github.event.number }}
          else
            echo "Test app already exists."
          fi

      - name: Deploy Test App to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --app orbit-api-pr-${{ github.event.number }} --config fly.toml --remote-only

      - name: Delete Test App from Fly.io
        if: always()
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl apps destroy orbit-api-pr-${{ github.event.number }} --yes